### ISSUE TITLE
0.11.3: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [jbms/sphinx-immaterial#242]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

Here is pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-immaterial-0.11.3-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-immaterial-0.11.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-immaterial-0.11.3
configfile: pyproject.toml
testpaths: tests
collected 30 items / 1 error

========================================================================================== ERRORS ===========================================================================================
____________________________________________________________________ ERROR collecting tests/issue_134/issue_134_test.py _____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/sphinx-immaterial-0.11.3/tests/issue_134/issue_134_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/site-packages/_pytest/python.py:622: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:564: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:172: in exec_module
    exec(co, module.__dict__)
tests/issue_134/issue_134_test.py:6: in <module>
    from sphinx_immaterial_pybind11_issue_134 import Example  # type: ignore
E   ModuleNotFoundError: No module named 'sphinx_immaterial_pybind11_issue_134'
================================================================================== short test summary info ==================================================================================
ERROR tests/issue_134/issue_134_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 1 error in 0.35s ======================================================================================
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.13
appdirs                       1.4.4
Babel                         2.12.1
build                         0.10.0
charset-normalizer            3.1.0
clang                         16.0.1.1
distro                        1.8.0
docutils                      0.19
exceptiongroup                1.0.0
gpg                           1.19.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.6.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.2
libcomps                      0.1.19
Markdown                      3.4.1
MarkupSafe                    2.1.2
packaging                     23.1
pluggy                        1.0.0
pydantic                      1.10.7
Pygments                      2.15.1
pymdown-extensions            9.11
pyproject_hooks               1.0.0
pytest                        7.3.1
python-dateutil               2.8.2
pytz                          2023.2
PyYAML                        6.0
requests                      2.28.2
setuptools                    67.6.1
setuptools-scm                7.1.0
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        6.1.3
sphinx-jinja                  2.0.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2.dev20230415
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20230415
sphinxcontrib-qthelp          1.0.3.dev20230415
sphinxcontrib-serializinghtml 1.1.5
tomli                         2.0.1
typing_extensions             4.5.0
urllib3                       1.26.15
wheel                         0.40.0
zipp                          3.15.0
```
</details>

**Comment by 2bndy5** [comment]
Did you first run 
```
pip install -r tests/requirements.txt
```
We made a custom test package to ensure builds work with pybind11-made pkgs.

---
I suppose we should document the dev workflow for unit testing sphinx-immaterial.

**Comment by kloczek** [comment]
After add that file to --ignore list
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-immaterial-0.11.3-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-immaterial-0.11.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --ignore tests/issue_134/issue_134_test.py
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-immaterial-0.11.3
configfile: pyproject.toml
testpaths: tests
plugins: snapshot-0.9.0
collected 30 items

tests/cpp_api_parser_test.py::test_basic PASSED
tests/cpp_api_parser_test.py::test_enable_if_transform PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[///] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[//!] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[/**] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[/*!] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[///<] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[/** \n * \n */] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[/*! \n * \n */] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[// \n /// \n //] PASSED
tests/cpp_api_parser_test.py::TestCommentStrip::test_comment_styles[/* \n * \n */\n /** */\n /* */] PASSED
tests/cpp_api_parser_test.py::test_function_fields PASSED
tests/graphviz_test.py::test_square_brackets[with] PASSED
tests/graphviz_test.py::test_square_brackets[without] PASSED
tests/nav_adapt_test.py::test_nav[collapse_True-includeonly_True] PASSED
tests/nav_adapt_test.py::test_nav[collapse_True-includeonly_False] PASSED
tests/nav_adapt_test.py::test_nav[collapse_False-includeonly_True] PASSED
tests/nav_adapt_test.py::test_nav[collapse_False-includeonly_False] PASSED
tests/nav_adapt_test.py::test_include_rubrics_in_toc[True] Running Sphinx v6.1.3
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
writing additional pages... done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in ../../../../../tmp/pytest-of-tkloczko/pytest-493/test_include_rubrics_in_toc_Tr0/_build/html.

PASSED
tests/nav_adapt_test.py::test_include_rubrics_in_toc[False] Running Sphinx v6.1.3
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
writing additional pages... done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in ../../../../../tmp/pytest-of-tkloczko/pytest-493/test_include_rubrics_in_toc_Fa0/_build/html.

PASSED
tests/python_apigen_test.py::test_alphabetical[alphabetical-expected_members0] Running Sphinx v6.1.3


PASSED
tests/python_apigen_test.py::test_alphabetical[definition_order-expected_members1] Running Sphinx v6.1.3


PASSED
tests/python_apigen_test.py::test_classmethod Running Sphinx v6.1.3


PASSED
tests/python_apigen_test.py::test_issue_147 Running Sphinx v6.1.3


PASSED
tests/python_apigen_test.py::test_pybind11_property Running Sphinx v6.1.3

WARNING: Failed to import module sphinx_immaterial_pybind11_issue_134 specified in python_apigen_modules
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-immaterial-0.11.3-2.fc35.x86_64/usr/lib/python3.8/site-packages/sphinx_immaterial/apidoc/python/apigen.py", line 1655, in _builder_inited
    importlib.import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinx_immaterial_pybind11_issue_134'

FAILED
tests/python_apigen_test.py::test_pure_python_property Running Sphinx v6.1.3


PASSED
tests/python_object_ids_test.py::test_nonodeid PASSED
tests/python_synopsis_test.py::test_python_class_synopsis PASSED
tests/python_transform_type_annotations_test.py::test_transform_type_annotations_pep604 PASSED
tests/search_index_test.py::test_object_anchor PASSED

========================================================================================= FAILURES ==========================================================================================
__________________________________________________________________________________ test_pybind11_property ___________________________________________________________________________________

apigen_make_app = <function apigen_make_app.<locals>.make at 0x7f63131f8790>

    def test_pybind11_property(apigen_make_app):
        testmod = "sphinx_immaterial_pybind11_issue_134"
        app = apigen_make_app(
            confoverrides=dict(
                python_apigen_modules={
                    testmod: "api/",
                },
            ),
        )
        print(app._status.getvalue())
        print(app._warning.getvalue())

        data = _get_api_data(app.env)

>       options = data.entities[f"{testmod}.Example.is_set_by_init"].options
E       KeyError: 'sphinx_immaterial_pybind11_issue_134.Example.is_set_by_init'

tests/python_apigen_test.py:117: KeyError
===================================================================================== warnings summary ======================================================================================
tests/graphviz_test.py::test_square_brackets[with]
tests/graphviz_test.py::test_square_brackets[with]
  /usr/lib64/python3.8/importlib/__init__.py:127: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
    return _bootstrap._gcd_import(name[level:], package, level)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ==================================================================================
FAILED tests/python_apigen_test.py::test_pybind11_property - KeyError: 'sphinx_immaterial_pybind11_issue_134.Example.is_set_by_init'
========================================================================= 1 failed, 29 passed, 2 warnings in 6.74s ==========================================================================
```
Issue is generally that pytest looks like should builld test module and at the same time it is required dring scanning for units.

Other two minor "issues"
- use spaces in units names
- hardcode defaiult verbose pytest mode

Generally if that test module needs to be build you have in ticket description how to call `build` module to use new pep517 build process.

**Comment by 2bndy5** [comment]
Yeah, the pybind11 test pkg is also used in 
https://github.com/jbms/sphinx-immaterial/blob/d91eacc94250c7fafb8b930ac744d3bbcffe50da/tests/python_apigen_test.py#L101

---
> pytest is executed with `-m "not network"`

Not entirely sure of the purpose for this. We don't have any tests marked "network"

**Comment by kloczek** [comment]
> Not entirely sure of the purpose for this. We don't have any tests marked "network"

You can ignore that patrt. It is part of my default rpm %pytest macro to disable units wich are marked as using public network access (many modules test provides over that pytest mark disable patr of the test suite which requiquires such access).

FYI in my build procedure I've added ignore and deselect failing parts
```spec
%pytest %{!?with_failing_tests: \
        --deselect tests/python_apigen_test.py::test_pybind11_property \
        --ignore tests/issue_134/issue_134_test.py \
}
```
As seems it is more issue with test suite than tested code it can be disabled to have some working base build 😋 

I've also added below patch
```patch
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -22,7 +22,6 @@

 [tool.pytest.ini_options]
 minversion = "6.0"
-addopts = "-vv -s"
 testpaths = ["tests"]

 [tool.pylint.main]
```
If you need verbose output better is to add -vv in CI execution.

With above pytest shows me now
```console
1.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --deselect tests/python_apigen_test.py::test_pybind11_property --ignore tests/issue_134/issue_134_test.py
============================= test session starts ==============================
platform linux -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-immaterial-0.11.3
configfile: pyproject.toml
testpaths: tests
plugins: snapshot-0.9.0
collected 30 items / 1 deselected / 29 selected

tests/cpp_api_parser_test.py ............                                [ 41%]
tests/graphviz_test.py ..                                                [ 48%]
tests/nav_adapt_test.py ......                                           [ 68%]
tests/python_apigen_test.py .....                                        [ 86%]
tests/python_object_ids_test.py .                                        [ 89%]
tests/python_synopsis_test.py .                                          [ 93%]
tests/python_transform_type_annotations_test.py .                        [ 96%]
tests/search_index_test.py .                                             [100%]

=============================== warnings summary ===============================
tests/graphviz_test.py::test_square_brackets[with]
tests/graphviz_test.py::test_square_brackets[with]
  /usr/lib64/python3.8/importlib/__init__.py:127: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
    return _bootstrap._gcd_import(name[level:], package, level)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 29 passed, 1 deselected, 2 warnings in 6.42s =================
```

**Comment by 2bndy5** [comment]
Your wording (& missing punctuation) is a bit confusing to me.

> Issue is generally that pytest looks like should builld test module and at the same time it is required dring scanning for units.

Pytest doesn't (& shouldn't) build the pybind11 test pkg, rather that should be done as a pre-requisite before invoking pytest. This aligns with installing other test dependencies, but the problem is that it isn't a pure python source.

> As seems it is more issue with test suite than tested code it can be disabled to have some working base build

All of our tests are created from addressing issues that were previously raised. Thus, our "base build" is better verified when all units pass.

> If you need verbose output better is to add `-vv` in CI execution.

This was done so we can run pytest locally the same as it in CI. However, it would be trivial to add it to our noxfile.py instead of in pyproject.toml. `-s` is just there because we don't analyze the `spihinx-build` output; there are more programmatic ways that we employ.

---
Our CI doesn't use the `build` pkg, but we may need to update that to keep using `setuptools_scm` to get the git tag for version spec. I recently had to do this for a pybind11-enabled pkg I released for a personal C++ project.

**Comment by kloczek** [comment]
> our wording (& missing punctuation) is a bit confusing to me.

Sorry. .. my fault 😞 

> Our CI doesn't use the `build` pkg, but we may need to update that to keep using `setuptools_scm` to get the git tag for version spec. I recently had to do this for a pybind11-enabled pkg I released for a personal C++ project.

On use pep571 with `build` module `setuptools_scm` is only pep517 backednd.
No matter which one backedd is used (setuptools, setuptools-scm, whey , pdm, poetry-core, hatch, hachlings ..) always whole build procedure will look exactly the same.
